// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/docker/app/internal/com/front-service.proto

/*
	Package com is a generated protocol buffer package.

	It is generated from these files:
		github.com/docker/app/internal/com/front-service.proto

	It has these top-level messages:
		FileStat
		VersionMismatch
		UntarPacket
*/
package com

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/types"
import google_protobuf1 "github.com/gogo/protobuf/types"

import bytes "bytes"

import strings "strings"
import reflect "reflect"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type FileStat struct {
	Name  string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Mode  int32  `protobuf:"varint,2,opt,name=Mode,proto3" json:"Mode,omitempty"`
	IsDir bool   `protobuf:"varint,3,opt,name=IsDir,proto3" json:"IsDir,omitempty"`
}

func (m *FileStat) Reset()                    { *m = FileStat{} }
func (*FileStat) ProtoMessage()               {}
func (*FileStat) Descriptor() ([]byte, []int) { return fileDescriptorFrontService, []int{0} }

func (m *FileStat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileStat) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *FileStat) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

type VersionMismatch struct {
	BackendVersion string `protobuf:"bytes,1,opt,name=BackendVersion,proto3" json:"BackendVersion,omitempty"`
	PackageVersion string `protobuf:"bytes,2,opt,name=PackageVersion,proto3" json:"PackageVersion,omitempty"`
}

func (m *VersionMismatch) Reset()                    { *m = VersionMismatch{} }
func (*VersionMismatch) ProtoMessage()               {}
func (*VersionMismatch) Descriptor() ([]byte, []int) { return fileDescriptorFrontService, []int{1} }

func (m *VersionMismatch) GetBackendVersion() string {
	if m != nil {
		return m.BackendVersion
	}
	return ""
}

func (m *VersionMismatch) GetPackageVersion() string {
	if m != nil {
		return m.PackageVersion
	}
	return ""
}

type UntarPacket struct {
	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Dest string `protobuf:"bytes,2,opt,name=Dest,proto3" json:"Dest,omitempty"`
}

func (m *UntarPacket) Reset()                    { *m = UntarPacket{} }
func (*UntarPacket) ProtoMessage()               {}
func (*UntarPacket) Descriptor() ([]byte, []int) { return fileDescriptorFrontService, []int{2} }

func (m *UntarPacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UntarPacket) GetDest() string {
	if m != nil {
		return m.Dest
	}
	return ""
}

func init() {
	proto.RegisterType((*FileStat)(nil), "com.FileStat")
	proto.RegisterType((*VersionMismatch)(nil), "com.VersionMismatch")
	proto.RegisterType((*UntarPacket)(nil), "com.UntarPacket")
}
func (this *FileStat) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FileStat)
	if !ok {
		that2, ok := that.(FileStat)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Mode != that1.Mode {
		return false
	}
	if this.IsDir != that1.IsDir {
		return false
	}
	return true
}
func (this *VersionMismatch) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VersionMismatch)
	if !ok {
		that2, ok := that.(VersionMismatch)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BackendVersion != that1.BackendVersion {
		return false
	}
	if this.PackageVersion != that1.PackageVersion {
		return false
	}
	return true
}
func (this *UntarPacket) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UntarPacket)
	if !ok {
		that2, ok := that.(UntarPacket)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Data, that1.Data) {
		return false
	}
	if this.Dest != that1.Dest {
		return false
	}
	return true
}
func (this *FileStat) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&com.FileStat{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Mode: "+fmt.Sprintf("%#v", this.Mode)+",\n")
	s = append(s, "IsDir: "+fmt.Sprintf("%#v", this.IsDir)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *VersionMismatch) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&com.VersionMismatch{")
	s = append(s, "BackendVersion: "+fmt.Sprintf("%#v", this.BackendVersion)+",\n")
	s = append(s, "PackageVersion: "+fmt.Sprintf("%#v", this.PackageVersion)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *UntarPacket) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&com.UntarPacket{")
	s = append(s, "Data: "+fmt.Sprintf("%#v", this.Data)+",\n")
	s = append(s, "Dest: "+fmt.Sprintf("%#v", this.Dest)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringFrontService(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FrontService service

type FrontServiceClient interface {
	FileContent(ctx context.Context, in *google_protobuf1.StringValue, opts ...grpc.CallOption) (FrontService_FileContentClient, error)
	FileList(ctx context.Context, in *google_protobuf1.StringValue, opts ...grpc.CallOption) (FrontService_FileListClient, error)
	TarDir(ctx context.Context, in *google_protobuf1.StringValue, opts ...grpc.CallOption) (FrontService_TarDirClient, error)
	UntarDir(ctx context.Context, opts ...grpc.CallOption) (FrontService_UntarDirClient, error)
}

type frontServiceClient struct {
	cc *grpc.ClientConn
}

func NewFrontServiceClient(cc *grpc.ClientConn) FrontServiceClient {
	return &frontServiceClient{cc}
}

func (c *frontServiceClient) FileContent(ctx context.Context, in *google_protobuf1.StringValue, opts ...grpc.CallOption) (FrontService_FileContentClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FrontService_serviceDesc.Streams[0], c.cc, "/com.FrontService/FileContent", opts...)
	if err != nil {
		return nil, err
	}
	x := &frontServiceFileContentClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FrontService_FileContentClient interface {
	Recv() (*google_protobuf1.BytesValue, error)
	grpc.ClientStream
}

type frontServiceFileContentClient struct {
	grpc.ClientStream
}

func (x *frontServiceFileContentClient) Recv() (*google_protobuf1.BytesValue, error) {
	m := new(google_protobuf1.BytesValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *frontServiceClient) FileList(ctx context.Context, in *google_protobuf1.StringValue, opts ...grpc.CallOption) (FrontService_FileListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FrontService_serviceDesc.Streams[1], c.cc, "/com.FrontService/FileList", opts...)
	if err != nil {
		return nil, err
	}
	x := &frontServiceFileListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FrontService_FileListClient interface {
	Recv() (*FileStat, error)
	grpc.ClientStream
}

type frontServiceFileListClient struct {
	grpc.ClientStream
}

func (x *frontServiceFileListClient) Recv() (*FileStat, error) {
	m := new(FileStat)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *frontServiceClient) TarDir(ctx context.Context, in *google_protobuf1.StringValue, opts ...grpc.CallOption) (FrontService_TarDirClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FrontService_serviceDesc.Streams[2], c.cc, "/com.FrontService/TarDir", opts...)
	if err != nil {
		return nil, err
	}
	x := &frontServiceTarDirClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FrontService_TarDirClient interface {
	Recv() (*google_protobuf1.BytesValue, error)
	grpc.ClientStream
}

type frontServiceTarDirClient struct {
	grpc.ClientStream
}

func (x *frontServiceTarDirClient) Recv() (*google_protobuf1.BytesValue, error) {
	m := new(google_protobuf1.BytesValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *frontServiceClient) UntarDir(ctx context.Context, opts ...grpc.CallOption) (FrontService_UntarDirClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FrontService_serviceDesc.Streams[3], c.cc, "/com.FrontService/UntarDir", opts...)
	if err != nil {
		return nil, err
	}
	x := &frontServiceUntarDirClient{stream}
	return x, nil
}

type FrontService_UntarDirClient interface {
	Send(*UntarPacket) error
	CloseAndRecv() (*google_protobuf.Empty, error)
	grpc.ClientStream
}

type frontServiceUntarDirClient struct {
	grpc.ClientStream
}

func (x *frontServiceUntarDirClient) Send(m *UntarPacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *frontServiceUntarDirClient) CloseAndRecv() (*google_protobuf.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(google_protobuf.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for FrontService service

type FrontServiceServer interface {
	FileContent(*google_protobuf1.StringValue, FrontService_FileContentServer) error
	FileList(*google_protobuf1.StringValue, FrontService_FileListServer) error
	TarDir(*google_protobuf1.StringValue, FrontService_TarDirServer) error
	UntarDir(FrontService_UntarDirServer) error
}

func RegisterFrontServiceServer(s *grpc.Server, srv FrontServiceServer) {
	s.RegisterService(&_FrontService_serviceDesc, srv)
}

func _FrontService_FileContent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf1.StringValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FrontServiceServer).FileContent(m, &frontServiceFileContentServer{stream})
}

type FrontService_FileContentServer interface {
	Send(*google_protobuf1.BytesValue) error
	grpc.ServerStream
}

type frontServiceFileContentServer struct {
	grpc.ServerStream
}

func (x *frontServiceFileContentServer) Send(m *google_protobuf1.BytesValue) error {
	return x.ServerStream.SendMsg(m)
}

func _FrontService_FileList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf1.StringValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FrontServiceServer).FileList(m, &frontServiceFileListServer{stream})
}

type FrontService_FileListServer interface {
	Send(*FileStat) error
	grpc.ServerStream
}

type frontServiceFileListServer struct {
	grpc.ServerStream
}

func (x *frontServiceFileListServer) Send(m *FileStat) error {
	return x.ServerStream.SendMsg(m)
}

func _FrontService_TarDir_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf1.StringValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FrontServiceServer).TarDir(m, &frontServiceTarDirServer{stream})
}

type FrontService_TarDirServer interface {
	Send(*google_protobuf1.BytesValue) error
	grpc.ServerStream
}

type frontServiceTarDirServer struct {
	grpc.ServerStream
}

func (x *frontServiceTarDirServer) Send(m *google_protobuf1.BytesValue) error {
	return x.ServerStream.SendMsg(m)
}

func _FrontService_UntarDir_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FrontServiceServer).UntarDir(&frontServiceUntarDirServer{stream})
}

type FrontService_UntarDirServer interface {
	SendAndClose(*google_protobuf.Empty) error
	Recv() (*UntarPacket, error)
	grpc.ServerStream
}

type frontServiceUntarDirServer struct {
	grpc.ServerStream
}

func (x *frontServiceUntarDirServer) SendAndClose(m *google_protobuf.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *frontServiceUntarDirServer) Recv() (*UntarPacket, error) {
	m := new(UntarPacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FrontService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.FrontService",
	HandlerType: (*FrontServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FileContent",
			Handler:       _FrontService_FileContent_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FileList",
			Handler:       _FrontService_FileList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TarDir",
			Handler:       _FrontService_TarDir_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UntarDir",
			Handler:       _FrontService_UntarDir_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/docker/app/internal/com/front-service.proto",
}

// Client API for RemoteStdStreams service

type RemoteStdStreamsClient interface {
	Stdin(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (RemoteStdStreams_StdinClient, error)
	Stdout(ctx context.Context, opts ...grpc.CallOption) (RemoteStdStreams_StdoutClient, error)
	Stderr(ctx context.Context, opts ...grpc.CallOption) (RemoteStdStreams_StderrClient, error)
}

type remoteStdStreamsClient struct {
	cc *grpc.ClientConn
}

func NewRemoteStdStreamsClient(cc *grpc.ClientConn) RemoteStdStreamsClient {
	return &remoteStdStreamsClient{cc}
}

func (c *remoteStdStreamsClient) Stdin(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (RemoteStdStreams_StdinClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RemoteStdStreams_serviceDesc.Streams[0], c.cc, "/com.RemoteStdStreams/Stdin", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteStdStreamsStdinClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RemoteStdStreams_StdinClient interface {
	Recv() (*google_protobuf1.BytesValue, error)
	grpc.ClientStream
}

type remoteStdStreamsStdinClient struct {
	grpc.ClientStream
}

func (x *remoteStdStreamsStdinClient) Recv() (*google_protobuf1.BytesValue, error) {
	m := new(google_protobuf1.BytesValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *remoteStdStreamsClient) Stdout(ctx context.Context, opts ...grpc.CallOption) (RemoteStdStreams_StdoutClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RemoteStdStreams_serviceDesc.Streams[1], c.cc, "/com.RemoteStdStreams/Stdout", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteStdStreamsStdoutClient{stream}
	return x, nil
}

type RemoteStdStreams_StdoutClient interface {
	Send(*google_protobuf1.BytesValue) error
	CloseAndRecv() (*google_protobuf.Empty, error)
	grpc.ClientStream
}

type remoteStdStreamsStdoutClient struct {
	grpc.ClientStream
}

func (x *remoteStdStreamsStdoutClient) Send(m *google_protobuf1.BytesValue) error {
	return x.ClientStream.SendMsg(m)
}

func (x *remoteStdStreamsStdoutClient) CloseAndRecv() (*google_protobuf.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(google_protobuf.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *remoteStdStreamsClient) Stderr(ctx context.Context, opts ...grpc.CallOption) (RemoteStdStreams_StderrClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RemoteStdStreams_serviceDesc.Streams[2], c.cc, "/com.RemoteStdStreams/Stderr", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteStdStreamsStderrClient{stream}
	return x, nil
}

type RemoteStdStreams_StderrClient interface {
	Send(*google_protobuf1.BytesValue) error
	CloseAndRecv() (*google_protobuf.Empty, error)
	grpc.ClientStream
}

type remoteStdStreamsStderrClient struct {
	grpc.ClientStream
}

func (x *remoteStdStreamsStderrClient) Send(m *google_protobuf1.BytesValue) error {
	return x.ClientStream.SendMsg(m)
}

func (x *remoteStdStreamsStderrClient) CloseAndRecv() (*google_protobuf.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(google_protobuf.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RemoteStdStreams service

type RemoteStdStreamsServer interface {
	Stdin(*google_protobuf.Empty, RemoteStdStreams_StdinServer) error
	Stdout(RemoteStdStreams_StdoutServer) error
	Stderr(RemoteStdStreams_StderrServer) error
}

func RegisterRemoteStdStreamsServer(s *grpc.Server, srv RemoteStdStreamsServer) {
	s.RegisterService(&_RemoteStdStreams_serviceDesc, srv)
}

func _RemoteStdStreams_Stdin_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RemoteStdStreamsServer).Stdin(m, &remoteStdStreamsStdinServer{stream})
}

type RemoteStdStreams_StdinServer interface {
	Send(*google_protobuf1.BytesValue) error
	grpc.ServerStream
}

type remoteStdStreamsStdinServer struct {
	grpc.ServerStream
}

func (x *remoteStdStreamsStdinServer) Send(m *google_protobuf1.BytesValue) error {
	return x.ServerStream.SendMsg(m)
}

func _RemoteStdStreams_Stdout_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteStdStreamsServer).Stdout(&remoteStdStreamsStdoutServer{stream})
}

type RemoteStdStreams_StdoutServer interface {
	SendAndClose(*google_protobuf.Empty) error
	Recv() (*google_protobuf1.BytesValue, error)
	grpc.ServerStream
}

type remoteStdStreamsStdoutServer struct {
	grpc.ServerStream
}

func (x *remoteStdStreamsStdoutServer) SendAndClose(m *google_protobuf.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *remoteStdStreamsStdoutServer) Recv() (*google_protobuf1.BytesValue, error) {
	m := new(google_protobuf1.BytesValue)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RemoteStdStreams_Stderr_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteStdStreamsServer).Stderr(&remoteStdStreamsStderrServer{stream})
}

type RemoteStdStreams_StderrServer interface {
	SendAndClose(*google_protobuf.Empty) error
	Recv() (*google_protobuf1.BytesValue, error)
	grpc.ServerStream
}

type remoteStdStreamsStderrServer struct {
	grpc.ServerStream
}

func (x *remoteStdStreamsStderrServer) SendAndClose(m *google_protobuf.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *remoteStdStreamsStderrServer) Recv() (*google_protobuf1.BytesValue, error) {
	m := new(google_protobuf1.BytesValue)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RemoteStdStreams_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.RemoteStdStreams",
	HandlerType: (*RemoteStdStreamsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stdin",
			Handler:       _RemoteStdStreams_Stdin_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Stdout",
			Handler:       _RemoteStdStreams_Stdout_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Stderr",
			Handler:       _RemoteStdStreams_Stderr_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/docker/app/internal/com/front-service.proto",
}

// Client API for Session service

type SessionClient interface {
	EndSession(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	BackendVersionMismatch(ctx context.Context, in *VersionMismatch, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type sessionClient struct {
	cc *grpc.ClientConn
}

func NewSessionClient(cc *grpc.ClientConn) SessionClient {
	return &sessionClient{cc}
}

func (c *sessionClient) EndSession(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/com.Session/EndSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) BackendVersionMismatch(ctx context.Context, in *VersionMismatch, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/com.Session/BackendVersionMismatch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Session service

type SessionServer interface {
	EndSession(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
	BackendVersionMismatch(context.Context, *VersionMismatch) (*google_protobuf.Empty, error)
}

func RegisterSessionServer(s *grpc.Server, srv SessionServer) {
	s.RegisterService(&_Session_serviceDesc, srv)
}

func _Session_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.Session/EndSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).EndSession(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_BackendVersionMismatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionMismatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).BackendVersionMismatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.Session/BackendVersionMismatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).BackendVersionMismatch(ctx, req.(*VersionMismatch))
	}
	return interceptor(ctx, in, info, handler)
}

var _Session_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.Session",
	HandlerType: (*SessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EndSession",
			Handler:    _Session_EndSession_Handler,
		},
		{
			MethodName: "BackendVersionMismatch",
			Handler:    _Session_BackendVersionMismatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/docker/app/internal/com/front-service.proto",
}

func (m *FileStat) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FileStat) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintFrontService(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.Mode != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintFrontService(dAtA, i, uint64(m.Mode))
	}
	if m.IsDir {
		dAtA[i] = 0x18
		i++
		if m.IsDir {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *VersionMismatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VersionMismatch) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.BackendVersion) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintFrontService(dAtA, i, uint64(len(m.BackendVersion)))
		i += copy(dAtA[i:], m.BackendVersion)
	}
	if len(m.PackageVersion) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintFrontService(dAtA, i, uint64(len(m.PackageVersion)))
		i += copy(dAtA[i:], m.PackageVersion)
	}
	return i, nil
}

func (m *UntarPacket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UntarPacket) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintFrontService(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	if len(m.Dest) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintFrontService(dAtA, i, uint64(len(m.Dest)))
		i += copy(dAtA[i:], m.Dest)
	}
	return i, nil
}

func encodeVarintFrontService(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *FileStat) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovFrontService(uint64(l))
	}
	if m.Mode != 0 {
		n += 1 + sovFrontService(uint64(m.Mode))
	}
	if m.IsDir {
		n += 2
	}
	return n
}

func (m *VersionMismatch) Size() (n int) {
	var l int
	_ = l
	l = len(m.BackendVersion)
	if l > 0 {
		n += 1 + l + sovFrontService(uint64(l))
	}
	l = len(m.PackageVersion)
	if l > 0 {
		n += 1 + l + sovFrontService(uint64(l))
	}
	return n
}

func (m *UntarPacket) Size() (n int) {
	var l int
	_ = l
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovFrontService(uint64(l))
	}
	l = len(m.Dest)
	if l > 0 {
		n += 1 + l + sovFrontService(uint64(l))
	}
	return n
}

func sovFrontService(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozFrontService(x uint64) (n int) {
	return sovFrontService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *FileStat) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FileStat{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Mode:` + fmt.Sprintf("%v", this.Mode) + `,`,
		`IsDir:` + fmt.Sprintf("%v", this.IsDir) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VersionMismatch) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VersionMismatch{`,
		`BackendVersion:` + fmt.Sprintf("%v", this.BackendVersion) + `,`,
		`PackageVersion:` + fmt.Sprintf("%v", this.PackageVersion) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UntarPacket) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UntarPacket{`,
		`Data:` + fmt.Sprintf("%v", this.Data) + `,`,
		`Dest:` + fmt.Sprintf("%v", this.Dest) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringFrontService(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *FileStat) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFrontService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FileStat: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FileStat: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFrontService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			m.Mode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsDir", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsDir = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipFrontService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFrontService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VersionMismatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFrontService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VersionMismatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VersionMismatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BackendVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFrontService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BackendVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PackageVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFrontService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PackageVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFrontService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFrontService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UntarPacket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFrontService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UntarPacket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UntarPacket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFrontService
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFrontService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dest = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFrontService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFrontService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFrontService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFrontService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthFrontService
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowFrontService
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipFrontService(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthFrontService = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFrontService   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("github.com/docker/app/internal/com/front-service.proto", fileDescriptorFrontService)
}

var fileDescriptorFrontService = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xce, 0xb4, 0x26, 0xc6, 0x69, 0xd5, 0x32, 0x94, 0x12, 0x52, 0x19, 0x42, 0x0e, 0x92, 0x83,
	0xee, 0x96, 0x88, 0x05, 0x41, 0x14, 0x62, 0x12, 0x54, 0xac, 0x48, 0x56, 0x7b, 0x9f, 0xec, 0xbe,
	0x6e, 0x87, 0x64, 0x67, 0x96, 0x99, 0x17, 0xa5, 0x37, 0xff, 0x81, 0x1e, 0xfc, 0x11, 0xfe, 0x14,
	0x8f, 0x3d, 0x78, 0xf0, 0x68, 0xd6, 0x8b, 0xc7, 0xfe, 0x04, 0xd9, 0xd9, 0x44, 0x6c, 0xca, 0x5a,
	0xd0, 0xdb, 0x9b, 0xef, 0xfb, 0xde, 0xb7, 0xef, 0x7d, 0xfb, 0xe8, 0x7e, 0x2c, 0xf1, 0x78, 0x36,
	0xf6, 0x42, 0x9d, 0xf8, 0x91, 0x0e, 0x27, 0x60, 0x7c, 0x91, 0xa6, 0xbe, 0x54, 0x08, 0x46, 0x89,
	0xa9, 0x9f, 0xe3, 0x47, 0x46, 0x2b, 0xbc, 0x6b, 0xc1, 0xbc, 0x95, 0x21, 0x78, 0xa9, 0xd1, 0xa8,
	0xd9, 0x7a, 0xa8, 0x93, 0xe6, 0x6e, 0xac, 0x75, 0x3c, 0x05, 0xdf, 0x41, 0xe3, 0xd9, 0x91, 0x0f,
	0x49, 0x8a, 0x27, 0x85, 0xa2, 0xc9, 0x57, 0xc9, 0x77, 0x46, 0xa4, 0x29, 0x18, 0x5b, 0xf0, 0xed,
	0xa7, 0xb4, 0x3e, 0x94, 0x53, 0x08, 0x50, 0x20, 0x63, 0xf4, 0xca, 0x4b, 0x91, 0x40, 0x83, 0xb4,
	0x48, 0xe7, 0xda, 0xc8, 0xd5, 0x39, 0x76, 0xa0, 0x23, 0x68, 0xac, 0xb5, 0x48, 0xa7, 0x3a, 0x72,
	0x35, 0xdb, 0xa6, 0xd5, 0x67, 0xb6, 0x2f, 0x4d, 0x63, 0xbd, 0x45, 0x3a, 0xf5, 0x51, 0xf1, 0x68,
	0x0b, 0x7a, 0xf3, 0x10, 0x8c, 0x95, 0x5a, 0x1d, 0x48, 0x9b, 0x08, 0x0c, 0x8f, 0xd9, 0x6d, 0x7a,
	0xa3, 0x27, 0xc2, 0x09, 0xa8, 0x68, 0xc1, 0x2c, 0xac, 0x57, 0xd0, 0x5c, 0xf7, 0x4a, 0x84, 0x13,
	0x11, 0xc3, 0x52, 0xb7, 0x56, 0xe8, 0xce, 0xa3, 0xed, 0xfb, 0x74, 0xe3, 0x8d, 0x42, 0x61, 0x72,
	0x18, 0xdc, 0xbc, 0x7d, 0x81, 0xc2, 0x99, 0x6e, 0x8e, 0x5c, 0xed, 0x30, 0xb0, 0xb8, 0x30, 0x70,
	0x75, 0xf7, 0xd3, 0x1a, 0xdd, 0x1c, 0xe6, 0xe9, 0x05, 0x45, 0x78, 0xec, 0x39, 0xdd, 0xc8, 0x97,
	0x7e, 0xa2, 0x15, 0x82, 0x42, 0x76, 0xcb, 0x2b, 0x42, 0xf2, 0x96, 0x21, 0x79, 0x01, 0x1a, 0xa9,
	0xe2, 0x43, 0x31, 0x9d, 0x41, 0x73, 0xf7, 0x02, 0xdb, 0x3b, 0x41, 0xb0, 0x8e, 0xdc, 0x23, 0xec,
	0x41, 0x11, 0xe0, 0x0b, 0x69, 0x2f, 0x33, 0xba, 0x9e, 0xff, 0x5e, 0x6f, 0x99, 0xf6, 0x1e, 0x61,
	0x03, 0x5a, 0x7b, 0x2d, 0x4c, 0x5f, 0x9a, 0xff, 0x9b, 0x60, 0x9f, 0xd6, 0x5d, 0x2a, 0xb9, 0xd1,
	0x96, 0xfb, 0xc6, 0x1f, 0x21, 0x35, 0x77, 0x2e, 0x34, 0x0f, 0xf2, 0xf3, 0xe8, 0x90, 0xee, 0x57,
	0x42, 0xb7, 0x46, 0x90, 0x68, 0x84, 0x00, 0xa3, 0x00, 0x0d, 0x88, 0xc4, 0xb2, 0x47, 0xb4, 0x1a,
	0x60, 0x24, 0x15, 0x2b, 0xe9, 0xbb, 0x6c, 0x98, 0xc7, 0xb4, 0x16, 0x60, 0xa4, 0x67, 0xc8, 0xfe,
	0x26, 0x2c, 0x9f, 0x6a, 0x61, 0x00, 0xc6, 0xfc, 0xa3, 0x41, 0xf7, 0x03, 0xa1, 0x57, 0x03, 0xb0,
	0xee, 0xb0, 0x1e, 0x52, 0x3a, 0x50, 0xd1, 0xf2, 0x55, 0xb6, 0x52, 0x09, 0xce, 0x86, 0x74, 0xe7,
	0xfc, 0xa1, 0xfe, 0x3e, 0xec, 0x6d, 0x17, 0xf3, 0x0a, 0x5a, 0xe6, 0xd3, 0xbb, 0x73, 0x3a, 0xe7,
	0x95, 0x6f, 0x73, 0x5e, 0x39, 0x9b, 0x73, 0xf2, 0x3e, 0xe3, 0xe4, 0x73, 0xc6, 0xc9, 0x97, 0x8c,
	0x93, 0xd3, 0x8c, 0x93, 0xef, 0x19, 0x27, 0x3f, 0x33, 0x5e, 0x39, 0xcb, 0x38, 0xf9, 0xf8, 0x83,
	0x57, 0xc6, 0x35, 0xd7, 0x7d, 0xef, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0x8c, 0x33, 0xe5,
	0x14, 0x04, 0x00, 0x00,
}
