// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/docker/app/internal/com/front-service.proto

/*
	Package com is a generated protocol buffer package.

	It is generated from these files:
		github.com/docker/app/internal/com/front-service.proto

	It has these top-level messages:
		PrintRequest
		FileStat
*/
package com

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/types"
import google_protobuf1 "github.com/gogo/protobuf/types"

import bytes "bytes"

import strings "strings"
import reflect "reflect"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type PrintRequest struct {
	Bytes     []byte `protobuf:"bytes,1,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	UseStdErr bool   `protobuf:"varint,2,opt,name=UseStdErr,proto3" json:"UseStdErr,omitempty"`
}

func (m *PrintRequest) Reset()                    { *m = PrintRequest{} }
func (*PrintRequest) ProtoMessage()               {}
func (*PrintRequest) Descriptor() ([]byte, []int) { return fileDescriptorFrontService, []int{0} }

func (m *PrintRequest) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *PrintRequest) GetUseStdErr() bool {
	if m != nil {
		return m.UseStdErr
	}
	return false
}

type FileStat struct {
	Name  string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Mode  int32  `protobuf:"varint,2,opt,name=Mode,proto3" json:"Mode,omitempty"`
	IsDir bool   `protobuf:"varint,3,opt,name=IsDir,proto3" json:"IsDir,omitempty"`
}

func (m *FileStat) Reset()                    { *m = FileStat{} }
func (*FileStat) ProtoMessage()               {}
func (*FileStat) Descriptor() ([]byte, []int) { return fileDescriptorFrontService, []int{1} }

func (m *FileStat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileStat) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *FileStat) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func init() {
	proto.RegisterType((*PrintRequest)(nil), "com.PrintRequest")
	proto.RegisterType((*FileStat)(nil), "com.FileStat")
}
func (this *PrintRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PrintRequest)
	if !ok {
		that2, ok := that.(PrintRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Bytes, that1.Bytes) {
		return false
	}
	if this.UseStdErr != that1.UseStdErr {
		return false
	}
	return true
}
func (this *FileStat) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FileStat)
	if !ok {
		that2, ok := that.(FileStat)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Mode != that1.Mode {
		return false
	}
	if this.IsDir != that1.IsDir {
		return false
	}
	return true
}
func (this *PrintRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&com.PrintRequest{")
	s = append(s, "Bytes: "+fmt.Sprintf("%#v", this.Bytes)+",\n")
	s = append(s, "UseStdErr: "+fmt.Sprintf("%#v", this.UseStdErr)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *FileStat) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&com.FileStat{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Mode: "+fmt.Sprintf("%#v", this.Mode)+",\n")
	s = append(s, "IsDir: "+fmt.Sprintf("%#v", this.IsDir)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringFrontService(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FrontService service

type FrontServiceClient interface {
	Prompt(ctx context.Context, in *google_protobuf1.BytesValue, opts ...grpc.CallOption) (*google_protobuf1.BytesValue, error)
	Print(ctx context.Context, in *PrintRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	FileContent(ctx context.Context, in *google_protobuf1.StringValue, opts ...grpc.CallOption) (FrontService_FileContentClient, error)
	FileList(ctx context.Context, in *google_protobuf1.StringValue, opts ...grpc.CallOption) (FrontService_FileListClient, error)
}

type frontServiceClient struct {
	cc *grpc.ClientConn
}

func NewFrontServiceClient(cc *grpc.ClientConn) FrontServiceClient {
	return &frontServiceClient{cc}
}

func (c *frontServiceClient) Prompt(ctx context.Context, in *google_protobuf1.BytesValue, opts ...grpc.CallOption) (*google_protobuf1.BytesValue, error) {
	out := new(google_protobuf1.BytesValue)
	err := grpc.Invoke(ctx, "/com.FrontService/Prompt", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontServiceClient) Print(ctx context.Context, in *PrintRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/com.FrontService/Print", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontServiceClient) FileContent(ctx context.Context, in *google_protobuf1.StringValue, opts ...grpc.CallOption) (FrontService_FileContentClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FrontService_serviceDesc.Streams[0], c.cc, "/com.FrontService/FileContent", opts...)
	if err != nil {
		return nil, err
	}
	x := &frontServiceFileContentClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FrontService_FileContentClient interface {
	Recv() (*google_protobuf1.BytesValue, error)
	grpc.ClientStream
}

type frontServiceFileContentClient struct {
	grpc.ClientStream
}

func (x *frontServiceFileContentClient) Recv() (*google_protobuf1.BytesValue, error) {
	m := new(google_protobuf1.BytesValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *frontServiceClient) FileList(ctx context.Context, in *google_protobuf1.StringValue, opts ...grpc.CallOption) (FrontService_FileListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FrontService_serviceDesc.Streams[1], c.cc, "/com.FrontService/FileList", opts...)
	if err != nil {
		return nil, err
	}
	x := &frontServiceFileListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FrontService_FileListClient interface {
	Recv() (*FileStat, error)
	grpc.ClientStream
}

type frontServiceFileListClient struct {
	grpc.ClientStream
}

func (x *frontServiceFileListClient) Recv() (*FileStat, error) {
	m := new(FileStat)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for FrontService service

type FrontServiceServer interface {
	Prompt(context.Context, *google_protobuf1.BytesValue) (*google_protobuf1.BytesValue, error)
	Print(context.Context, *PrintRequest) (*google_protobuf.Empty, error)
	FileContent(*google_protobuf1.StringValue, FrontService_FileContentServer) error
	FileList(*google_protobuf1.StringValue, FrontService_FileListServer) error
}

func RegisterFrontServiceServer(s *grpc.Server, srv FrontServiceServer) {
	s.RegisterService(&_FrontService_serviceDesc, srv)
}

func _FrontService_Prompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.BytesValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontServiceServer).Prompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.FrontService/Prompt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontServiceServer).Prompt(ctx, req.(*google_protobuf1.BytesValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontService_Print_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontServiceServer).Print(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.FrontService/Print",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontServiceServer).Print(ctx, req.(*PrintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontService_FileContent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf1.StringValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FrontServiceServer).FileContent(m, &frontServiceFileContentServer{stream})
}

type FrontService_FileContentServer interface {
	Send(*google_protobuf1.BytesValue) error
	grpc.ServerStream
}

type frontServiceFileContentServer struct {
	grpc.ServerStream
}

func (x *frontServiceFileContentServer) Send(m *google_protobuf1.BytesValue) error {
	return x.ServerStream.SendMsg(m)
}

func _FrontService_FileList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf1.StringValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FrontServiceServer).FileList(m, &frontServiceFileListServer{stream})
}

type FrontService_FileListServer interface {
	Send(*FileStat) error
	grpc.ServerStream
}

type frontServiceFileListServer struct {
	grpc.ServerStream
}

func (x *frontServiceFileListServer) Send(m *FileStat) error {
	return x.ServerStream.SendMsg(m)
}

var _FrontService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.FrontService",
	HandlerType: (*FrontServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prompt",
			Handler:    _FrontService_Prompt_Handler,
		},
		{
			MethodName: "Print",
			Handler:    _FrontService_Print_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FileContent",
			Handler:       _FrontService_FileContent_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FileList",
			Handler:       _FrontService_FileList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/docker/app/internal/com/front-service.proto",
}

func (m *PrintRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PrintRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Bytes) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintFrontService(dAtA, i, uint64(len(m.Bytes)))
		i += copy(dAtA[i:], m.Bytes)
	}
	if m.UseStdErr {
		dAtA[i] = 0x10
		i++
		if m.UseStdErr {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *FileStat) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FileStat) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintFrontService(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.Mode != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintFrontService(dAtA, i, uint64(m.Mode))
	}
	if m.IsDir {
		dAtA[i] = 0x18
		i++
		if m.IsDir {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func encodeVarintFrontService(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *PrintRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Bytes)
	if l > 0 {
		n += 1 + l + sovFrontService(uint64(l))
	}
	if m.UseStdErr {
		n += 2
	}
	return n
}

func (m *FileStat) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovFrontService(uint64(l))
	}
	if m.Mode != 0 {
		n += 1 + sovFrontService(uint64(m.Mode))
	}
	if m.IsDir {
		n += 2
	}
	return n
}

func sovFrontService(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozFrontService(x uint64) (n int) {
	return sovFrontService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *PrintRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PrintRequest{`,
		`Bytes:` + fmt.Sprintf("%v", this.Bytes) + `,`,
		`UseStdErr:` + fmt.Sprintf("%v", this.UseStdErr) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FileStat) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FileStat{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Mode:` + fmt.Sprintf("%v", this.Mode) + `,`,
		`IsDir:` + fmt.Sprintf("%v", this.IsDir) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringFrontService(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *PrintRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFrontService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PrintRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PrintRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bytes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFrontService
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bytes = append(m.Bytes[:0], dAtA[iNdEx:postIndex]...)
			if m.Bytes == nil {
				m.Bytes = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UseStdErr", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UseStdErr = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipFrontService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFrontService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FileStat) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFrontService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FileStat: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FileStat: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFrontService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			m.Mode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsDir", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsDir = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipFrontService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFrontService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFrontService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFrontService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFrontService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthFrontService
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowFrontService
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipFrontService(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthFrontService = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFrontService   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("github.com/docker/app/internal/com/front-service.proto", fileDescriptorFrontService)
}

var fileDescriptorFrontService = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4f, 0x4f, 0xe2, 0x40,
	0x18, 0xc6, 0x3b, 0xb0, 0x10, 0x98, 0x65, 0x0f, 0x3b, 0xd9, 0x6c, 0x48, 0x21, 0x13, 0xc2, 0x89,
	0xc3, 0x6e, 0x4b, 0x30, 0x31, 0xf1, 0x5a, 0x85, 0xa8, 0x51, 0x43, 0xda, 0xe8, 0xbd, 0x94, 0x97,
	0x3a, 0xb1, 0xed, 0xd4, 0xe9, 0x54, 0xc3, 0xcd, 0x2f, 0x60, 0xe2, 0xc7, 0xf0, 0xa3, 0x78, 0xe4,
	0xe8, 0x51, 0xea, 0xc5, 0x23, 0x1f, 0xc1, 0x74, 0x1a, 0xa2, 0x91, 0x44, 0x6e, 0xef, 0xfb, 0xbc,
	0x7f, 0x7f, 0x0f, 0xde, 0xf5, 0x99, 0xbc, 0x4c, 0x27, 0x86, 0xc7, 0x43, 0x73, 0xca, 0xbd, 0x2b,
	0x10, 0xa6, 0x1b, 0xc7, 0x26, 0x8b, 0x24, 0x88, 0xc8, 0x0d, 0xcc, 0x5c, 0x9f, 0x09, 0x1e, 0xc9,
	0xff, 0x09, 0x88, 0x1b, 0xe6, 0x81, 0x11, 0x0b, 0x2e, 0x39, 0x29, 0x7b, 0x3c, 0xd4, 0x5b, 0x3e,
	0xe7, 0x7e, 0x00, 0xa6, 0x92, 0x26, 0xe9, 0xcc, 0x84, 0x30, 0x96, 0xf3, 0xa2, 0x43, 0xa7, 0x5f,
	0x8b, 0xb7, 0xc2, 0x8d, 0x63, 0x10, 0x49, 0x51, 0xef, 0x5a, 0xb8, 0x31, 0x16, 0x2c, 0x92, 0x36,
	0x5c, 0xa7, 0x90, 0x48, 0xf2, 0x07, 0x57, 0xac, 0xb9, 0x84, 0xa4, 0x89, 0x3a, 0xa8, 0xd7, 0xb0,
	0x8b, 0x84, 0xb4, 0x71, 0xfd, 0x3c, 0x01, 0x47, 0x4e, 0x87, 0x42, 0x34, 0x4b, 0x1d, 0xd4, 0xab,
	0xd9, 0x1f, 0x42, 0xf7, 0x10, 0xd7, 0x46, 0x2c, 0x00, 0x47, 0xba, 0x92, 0x10, 0xfc, 0xe3, 0xcc,
	0x0d, 0x41, 0x8d, 0xd7, 0x6d, 0x15, 0xe7, 0xda, 0x29, 0x9f, 0x82, 0x1a, 0xac, 0xd8, 0x2a, 0xce,
	0xef, 0x1c, 0x25, 0x07, 0x4c, 0x34, 0xcb, 0x6a, 0x5b, 0x91, 0x0c, 0xee, 0x4b, 0xb8, 0x31, 0xca,
	0x39, 0x9d, 0x02, 0x93, 0x58, 0xb8, 0x3a, 0x16, 0x3c, 0x8c, 0x25, 0x69, 0x19, 0x05, 0x89, 0xb1,
	0x26, 0x31, 0xd4, 0x6b, 0x17, 0x6e, 0x90, 0x82, 0xfe, 0x5d, 0x91, 0x0c, 0x70, 0x45, 0x21, 0x92,
	0xdf, 0xb9, 0xbf, 0xc6, 0x67, 0x5c, 0xfd, 0xef, 0xc6, 0xe0, 0x30, 0x37, 0x8f, 0x1c, 0xe3, 0x9f,
	0x39, 0xd2, 0x3e, 0x8f, 0x24, 0x44, 0x92, 0xb4, 0x37, 0xda, 0x1c, 0x29, 0x58, 0xe4, 0x6f, 0xbf,
	0xde, 0x47, 0x64, 0xaf, 0xb0, 0xe7, 0x84, 0x25, 0xdb, 0x16, 0xfd, 0x52, 0x0f, 0xae, 0xbd, 0xec,
	0x23, 0xeb, 0xdf, 0x62, 0x49, 0xb5, 0xe7, 0x25, 0xd5, 0x56, 0x4b, 0x8a, 0xee, 0x32, 0x8a, 0x1e,
	0x33, 0x8a, 0x9e, 0x32, 0x8a, 0x16, 0x19, 0x45, 0x2f, 0x19, 0x45, 0x6f, 0x19, 0xd5, 0x56, 0x19,
	0x45, 0x0f, 0xaf, 0x54, 0x9b, 0x54, 0xd5, 0xd2, 0x9d, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08,
	0x6a, 0xfe, 0xc6, 0x4e, 0x02, 0x00, 0x00,
}
