#!/bin/sh

action=$CNAB_ACTION
name=$CNAB_INSTALLATION_NAME

case $action in
    install)
    echo "Install action"
    echo "boolParam=$BOOL_PARAM" 
    echo "stringParam=$STRING_PARAM" 
    echo "intParam=$INT_PARAM" 
    echo "floatParam=$FLOAT_PARAM" 
    ;;
    uninstall)
    echo "uninstall action"
    ;;
    upgrade)
    echo "Upgrade action"
    ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "Action $action complete for $name"
